name: aml_environment
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pytest==8.4.2
      - mlflow==2.6.0
      - pandas==2.3.3
      - scikit-learn==1.7.2
