channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - mlflow
      - cloudpickle
      - psutil
      - scikit-learn
      - pandas
      - azureml-core
      - azureml-defaults
      - azureml-mlflow
      - azureml-telemetry
      - pytest
name: basic-env-scikit