$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: basic-env-scikit
version: 1
description: Basic environment with scikit-learn and common data science packages
build:
  conda_file: |
    channels:
      - defaults
    dependencies:
      - python=3.12
      - pytest==8.4.2
      - mlflow==3.4.0
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - pip
