$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: basic-env-scikit
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04:latest
conda_file: conda.yml