name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

env:
  workspace-name: az-mlops
  resource-group: ml

jobs:
  train-dev:
    name: Train experiment model (dev)
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure ML job
      run: |
        az ml job create --file src/job-dev.yml --resource-group ${{env.resource-group}} --workspace-name ${{env.workspace-name}}

  train-prod:
    name: Train experiment model (prod)
    needs: [train-dev]
    runs-on: ubuntu-latest
    environment: 
      name: prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure ML job
      run: |
        az ml job create --file src/job-prod.yml --resource-group ${{env.resource-group}} --workspace-name ${{env.workspace-name}}


