name: Deploy Model to Azure ML Endpoint

on:
  workflow_dispatch:

env:
  workspace-name: az-mlops
  resource-group: ml

jobs:
  deploy:
    name: Deploy Latest registered model
    runs-on: ubuntu-latest
    environment: 
      name: prod
    
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Ensure resource providers are registered
        run: |
          az provider show --namespace Microsoft.MachineLearningServices --query "registrationState"

      - name: Create endpoint
        run: |
          az ml online-endpoint create \
            --file src/create-endpoint.yml \
            --resource-group ${{ env.resource-group }} \
            --workspace-name ${{ env.workspace-name }} || echo "Endpoint may already exist"

      - name: Deploy model to endpoint
        run: |
          az ml online-deployment create \
            --file src/deploy-endpoint.yml \
            --resource-group ${{ env.resource-group }} \
            --workspace-name ${{ env.workspace-name }} \
            --all-traffic
